package printer

import (
	"bytes"
	"fmt"
	"go/parser"
	"go/printer"
	"go/token"
	"text/template"

	"github.com/adamluo159/tabtoy/v2/i18n"
	"github.com/adamluo159/tabtoy/v2/model"
)

const goTemplate = `// Generated by github.com/adamluo159/tabtoy
// Version: {{.ToolVersion}}
// DO NOT EDIT!!
package {{.Package}}

import(	
	{{if .HasAnyIndex}}"fmt"{{end}}
	"encoding/json"
	"os"
	"sync/atomic"
)
{{range $a, $en := .Enums}} 
// Defined in table: {{$en.DefinedTable}}
type {{$en.Name}} int32
const (	
{{range .GoFields}}
	{{.Comment}}
	{{$en.Name}}_{{.Name}} {{$en.Name}} = {{.Number}}
{{end}}
)
var (
{{$en.Name}}MapperValueByName = map[string]int32{ {{range .GoFields}}
	"{{.Name}}": {{.Number}}, {{end}}
}

{{$en.Name}}MapperNameByValue = map[int32]string{ {{range .GoFields}}
	{{.Number}}: "{{.Name}}" , {{end}}
}

{{$en.Name}}CommentByValue = map[int32]string{ {{range .GoFields}}
	{{.Number}}: "{{.RawComment}}" , {{end}}
}

)

func (self {{$en.Name}}) String() string {
	name, _ := {{$en.Name}}MapperNameByValue[int32(self)]
	return name
}
{{end}}

{{range $a, $strus := .Structs}} 
// Defined in table: {{$strus.DefinedTable}}
type {{$strus.Name}} struct{
	{{range $b, $fd := $strus.GoFields}} 
	{{.Comment}}
	{{if .IsMap}}{{$fd.Name}} {{.MapTypeString}} {{$fd.StructTag}}{{else}}{{$fd.Name}} {{$fd.TypeString}} {{$fd.StructTag}}{{end}}
	{{end}}
}
{{end}}

// {{$.Name}} 访问接口
type {{$.Name}}Table struct{
    
	// 数据指针，使用原子操作进行更新
	data atomic.Pointer[{{$.Name}}Data]
	
	// 索引函数表
	indexFuncByName map[string][]func(*{{$.Name}}Table) error
	
	// 加载前回调
	preFuncList []func(*{{$.Name}}Table) error

	// 加载后回调
	postFuncList []func(*{{$.Name}}Table) error
}

// {{$.Name}} 数据结构体，用于写时复制
// 此结构体一旦创建，不应被修改
// 所有修改都通过创建新实例并原子替换data指针来实现
type {{$.Name}}Data struct{
	
	// 表格原始数据
	{{$.Name}}
	
	{{range $a, $strus := .IndexedStructs}} {{range .Indexes}}
{{if .IsOneToManyIndex}}{{$strus.Name}}By{{.Name}} map[{{.KeyType}}][]*{{$strus.TypeName}}
{{else}}{{$strus.Name}}By{{.Name}} map[{{.KeyType}}]*{{$strus.TypeName}}
{{end}}{{end}}{{end}}{{/* 联合索引字段定义 - 基于UnionIndex标记 */}}
{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}} map[struct{ K1 int32; K2 int32 }]*{{$strus.TypeName}}
{{end}}{{end}}{{end}}
}

{{range .VerticalFields}}
{{.Comment}}
func (self *{{$.Name}}Table) Get{{.Name}}( ) {{.ElementTypeString}} {
	return self.data.Load().{{.Name}}[0]
}
{{end}}

{{range .AllStructs}}
/** 获取{{.TypeName}}列表 */
func (self *{{$.Name}}Table) Get{{.TypeName}}s( ) []*{{.TypeName}} {
	return self.data.Load().{{.Name}}
}
{{end}}

{{range $strus := .IndexedStructs}} {{range .Indexes}}
/** 通过{{.Name}}获取{{$strus.TypeName}} */
{{if .IsOneToManyIndex}}
func (self *{{$.Name}}Table) Get{{$strus.TypeName}}By{{.Name}}(key {{.KeyType}}) []*{{$strus.TypeName}} {
	return self.data.Load().{{$strus.Name}}By{{.Name}}[key]
}
{{else}}
func (self *{{$.Name}}Table) Get{{$strus.TypeName}}By{{.Name}}(key {{.KeyType}}) *{{$strus.TypeName}} {
	return self.data.Load().{{$strus.Name}}By{{.Name}}[key]
}
{{end}}
{{end}}{{end}}{{/* 联合索引访问方法 - 基于UnionIndex标记 */}}
{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
/** 生成{{$strus.TypeName}}联合索引Key */
func Make{{$strus.TypeName}}Key{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}(k1 int32, k2 int32) struct{ K1 int32; K2 int32 } {
	return struct{ K1 int32; K2 int32 }{K1: k1, K2: k2}
}

/** 通过{{(index $unionFields 0).Name}}和{{(index $unionFields 1).Name}}获取{{$strus.TypeName}} */
func (self *{{$.Name}}Table) Get{{$strus.TypeName}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}(k1 int32, k2 int32) *{{$strus.TypeName}} {
	return self.data.Load().{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}[Make{{$strus.TypeName}}Key{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}(k1, k2)]
}
{{end}}{{end}}{{end}}


// 从json文件加载
func (self *{{$.Name}}Table) Load(filename string) error {
	data, err := os.ReadFile(filename)

	if err != nil {
		return err
	}

	return self.LoadData(data)
}

// 从目录加载拆分的json文件
func (self *{{$.Name}}Table) LoadFromDir(dir string) error {
	// 创建新的数据实例
	newData := &{{$.Name}}Data{}
	
	// 创建所有索引映射
	{{range $a, $strus := .IndexedStructs}} {{range .Indexes}}
{{if .IsOneToManyIndex}}	newData.{{$strus.Name}}By{{.Name}} = make(map[{{.KeyType}}][]*{{$strus.TypeName}})
{{else}}	newData.{{$strus.Name}}By{{.Name}} = make(map[{{.KeyType}}]*{{$strus.TypeName}})
{{end}}{{end}}{{end}}{{/* 联合索引初始化 - 基于UnionIndex标记 */}}
	{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
	newData.{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}} = make(map[struct{ K1 int32; K2 int32 }]*{{$strus.TypeName}})
	{{end}}{{end}}{{end}}
	
	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err := v(self); err != nil {
			return err
		}
	}

	// 加载每个表单的json文件
	{{range $a, $strus := .AllStructs}}
	{
		filename := fmt.Sprintf("%s/%s.json", dir, "{{$strus.Name}}")
		data, err := os.ReadFile(filename)
		if err != nil {
			return fmt.Errorf("load %s failed: %w", filename, err)
		}
		
		var items []*{{$strus.TypeName}}
		if err := json.Unmarshal(data, &items); err != nil {
			return fmt.Errorf("unmarshal %s failed: %w", filename, err)
		}
		newData.{{$strus.Name}} = items
	}
	{{end}}

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			// 创建临时表实例，用于索引生成
			tempTable := &{{$.Name}}Table{
				data: atomic.Pointer[{{$.Name}}Data]{},
			}
			tempTable.data.Store(newData)
			
			if err := v(tempTable); err != nil {
				return err
			}
		}
	}

	// 原子替换数据指针
	self.data.Store(newData)

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err := v(self); err != nil {
			return err
		}
	}

	return nil
}

// 从二进制加载
func (self *{{$.Name}}Table) LoadData(data []byte) error {
	var newTab {{$.Name}}

	// 读取
	err := json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 创建新的数据实例
	newData := &{{$.Name}}Data{
		{{$.Name}}: newTab,
	}
	
	// 创建所有索引映射
	{{range $a, $strus := .IndexedStructs}} {{range .Indexes}}
	newData.{{$strus.Name}}By{{.Name}} = make(map[{{.KeyType}}]*{{$strus.TypeName}})
	{{end}}{{end}}{{/* 联合索引初始化 - 基于UnionIndex标记 */}}
	{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
	newData.{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}} = make(map[struct{ K1 int32; K2 int32 }]*{{$strus.TypeName}})
	{{end}}{{end}}{{end}}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}
	
	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			// 创建临时表实例，用于索引生成
			tempTable := &{{$.Name}}Table{
				data: atomic.Pointer[{{$.Name}}Data]{},
			}
			tempTable.data.Store(newData)
			
			if err = v(tempTable); err != nil {
				return err
			}
		}
	}

	// 原子替换数据指针
	self.data.Store(newData)

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调
func (self *{{$.Name}}Table) RegisterIndexEntry(name string, indexCallback func(*{{$.Name}}Table) error) {
	if indexCallback == nil {
		return
	}
	
	indexList := self.indexFuncByName[name]
	indexList = append(indexList, indexCallback)
	self.indexFuncByName[name] = indexList
}

// 注册加载前回调
func (self *{{$.Name}}Table) RegisterPreEntry(callback func(*{{$.Name}}Table) error) {
	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *{{$.Name}}Table) RegisterPostEntry(callback func(*{{$.Name}}Table) error) {
	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个{{$.Name}}表读取实例
func New{{$.Name}}Table() *{{$.Name}}Table {
	// 创建初始数据实例
	initialData := &{{$.Name}}Data{}
	
	// 初始化所有索引映射
	{{range $a, $strus := .IndexedStructs}} {{range .Indexes}}
{{if .IsOneToManyIndex}}	initialData.{{$strus.Name}}By{{.Name}} = make(map[{{.KeyType}}][]*{{$strus.TypeName}})
{{else}}	initialData.{{$strus.Name}}By{{.Name}} = make(map[{{.KeyType}}]*{{$strus.TypeName}})
{{end}}{{end}}{{end}}{{/* 联合索引初始化 - 基于UnionIndex标记 */}}
	{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
	initialData.{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}} = make(map[struct{ K1 int32; K2 int32 }]*{{$strus.TypeName}})
	{{end}}{{end}}{{end}}
	
	table := &{{$.Name}}Table{
		indexFuncByName: map[string][]func(*{{$.Name}}Table) error{
		{{range $a, $strus := .IndexedStructs}}
		"{{$strus.Name}}": {func(tab *{{$.Name}}Table)error {
			
			// {{$strus.Name}}
			data := tab.data.Load()
			for _, def := range data.{{$strus.Name}} {
				{{range .Indexes}}
				{{if .IsOneToManyIndex}}
				// 一对多索引：允许重复key
				data.{{$strus.Name}}By{{.Name}}[def.{{.Name}}] = append(data.{{$strus.Name}}By{{.Name}}[def.{{.Name}}], def)
				{{else}}
				// 一对一索引：不允许重复key
				if _, ok := data.{{$strus.Name}}By{{.Name}}[def.{{.Name}}]; ok {
					return fmt.Errorf("duplicate index in {{$strus.Name}}By{{.Name}}: %v", def.{{.Name}})
				}
				data.{{$strus.Name}}By{{.Name}}[def.{{.Name}}] = def
				{{end}}
				{{end}}
				{{/* 联合索引构建逻辑 - 基于UnionIndex标记 */}}
				{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}
				{{if gt (len $unionFields) 1}}
				{{$idx1 := index $unionFields 0}}
				{{$idx2 := index $unionFields 1}}
				key := struct{ K1 int32; K2 int32 }{K1: def.{{$idx1.Name}}, K2: def.{{$idx2.Name}}}
				if _, ok := data.{{$strus.Name}}By{{$idx1.Name}}{{$idx2.Name}}[key]; ok {
					return fmt.Errorf("duplicate index in {{$strus.Name}}By{{$idx1.Name}}{{$idx2.Name}}: %v", key)
				}
				data.{{$strus.Name}}By{{$idx1.Name}}{{$idx2.Name}}[key] = def
				{{end}}
				{{end}}
			}

			return nil
		}},
	{{end}}			
			
		},
	}
	
	// 原子存储初始数据
	table.data.Store(initialData)
	
	return table
}
`

// 每个带有MakeIndex的列
type goFieldModel struct {
	*model.FieldDescriptor
	Number int
}

func (self *goFieldModel) Alias() string {
	return self.FieldDescriptor.Meta.GetString("Alias")
}

// IsOneToManyIndex 判断是否是一对多索引（只有MakeIndex没有RepeatCheck）
func (self *goFieldModel) IsOneToManyIndex() bool {
	return self.Meta.GetBool("MakeIndex") && !self.Meta.GetBool("RepeatCheck")
}

func (self *goFieldModel) RawComment() string {
	var out string

	if self.FieldDescriptor.Meta.GetString("Alias") != "" {
		return self.FieldDescriptor.Meta.GetString("Alias")
	}

	if self.FieldDescriptor.Comment != "" {
		return self.FieldDescriptor.Comment
	}
	return out
}

func (self *goFieldModel) Comment() string {

	var out string

	if self.FieldDescriptor.Comment != "" {
		return "//" + self.FieldDescriptor.Comment
	}

	if self.FieldDescriptor.Meta.GetString("Alias") != "" {
		return "//" + self.FieldDescriptor.Meta.GetString("Alias")
	}

	return out

}

func (self *goFieldModel) KeyType() string {

	// 修复: 当枚举做索引时, 多出包名
	if self.Type == model.FieldType_Enum {
		return self.Complex.Name
	}

	return model.FieldTypeToString(self.Type)
}

func (self *goFieldModel) StructTag() string {

	var buf bytes.Buffer

	buf.WriteString("`")

	var userTagCount int

	self.Meta.VisitUserMeta(func(k string, v interface{}) bool {

		if userTagCount > 0 {
			buf.WriteString(" ")
		}

		buf.WriteString(fmt.Sprintf("%s:\"%s\"", k, v))

		userTagCount++

		return true
	})

	buf.WriteString("`")

	if userTagCount == 0 {
		return ""
	}

	return buf.String()
}

func (self *goFieldModel) ElementTypeString() string {

	switch self.FieldDescriptor.Type {
	case model.FieldType_Float:
		return "float32"
	case model.FieldType_Struct:
		return "*" + self.FieldDescriptor.TypeString()
	default:
		return self.FieldDescriptor.TypeString()
	}
}

func (self *goFieldModel) TypeString() string {

	var prefix string
	if self.IsRepeated {
		prefix = "[]"
	}

	return prefix + self.ElementTypeString()

}

func (self *goFieldModel) IsMap() bool {
	return self.FieldDescriptor.Type == model.FieldType_Map
}

func (self *goFieldModel) MapKeyGoType() string {
	if self.FieldDescriptor.MapKeyType == model.FieldType_Enum {
		if self.FieldDescriptor.MapKeyComplex != nil {
			return self.FieldDescriptor.MapKeyComplex.Name
		}
	}
	return model.FieldTypeToString(self.FieldDescriptor.MapKeyType)
}

func (self *goFieldModel) MapValueGoType() string {
	switch self.FieldDescriptor.MapValueType {
	case model.FieldType_Struct:
		if self.FieldDescriptor.MapValueComplex != nil {
			return "*" + self.FieldDescriptor.MapValueComplex.Name
		}
	case model.FieldType_Enum:
		if self.FieldDescriptor.MapValueComplex != nil {
			return self.FieldDescriptor.MapValueComplex.Name
		}
	default:
		return model.FieldTypeToString(self.FieldDescriptor.MapValueType)
	}
	return model.FieldTypeToString(self.FieldDescriptor.MapValueType)
}

func (self *goFieldModel) MapTypeString() string {
	return "map[" + self.MapKeyGoType() + "]" + self.MapValueGoType()
}

// 对应每个电子表格文件
type goIndexStructModel struct {
	*model.FieldDescriptor

	Indexes []*goFieldModel
}

func (self *goIndexStructModel) TypeName() string {
	return self.Complex.Name
}

type goStructModel struct {
	*model.Descriptor

	GoFields []*goFieldModel
}

func (self *goStructModel) DefinedTable() string {
	return self.File.Name
}

// 整个导出文件
type goFileModel struct {
	*model.FileDescriptor
	ToolVersion    string
	IndexedStructs []*goIndexStructModel
	Structs        []*goStructModel
	Enums          []*goStructModel
	IndexCount     int
	AllStructs     []*goIndexStructModel
	PackageName    string

	// 配置的字段
	VerticalFields []*goFieldModel
}

func (self *goFileModel) HasAnyIndex() bool {
	return self.IndexCount > 0
}

func (self *goFileModel) HasAnyStruct() bool {
	return len(self.Structs) > 0
}

func (self *goFileModel) Package() string {
	// 优先使用命令行指定的包名，如果没有则使用表格中定义的包名
	if self.PackageName != "" {
		return self.PackageName
	}
	return self.FileDescriptor.Pragma.GetString("Package")
}

type goPrinter struct {
}

func collectIndexInfo(g *Globals, fm *goFileModel) {

	// 遍历需要导出的合并字段
	for _, fd := range g.CombineStruct.Fields {

		// fd --> 对应每个文件的Row定义, 也就是XXDefine, 在CombineStruct上, 只是一个字段

		// 对CombineStruct的XXDefine对应的字段
		if g.CombineStruct.Usage != model.DescriptorUsage_CombineStruct {
			continue
		}

		//非结构体不输出(其实根本不会击中)
		if fd.Complex == nil {
			continue
		}

		// 这个字段被限制输出
		if !fd.Complex.File.MatchTag(".go") {
			continue
		}

		// 这个结构有索引或联合索引才创建
		if len(fd.Complex.Indexes) == 0 && len(fd.Complex.UnionIndexes) == 0 {
			continue
		}

		rm := goIndexStructModel{
			FieldDescriptor: fd,
		}

		// 只收集单个索引字段，联合索引字段不生成单独索引
		for _, key := range fd.Complex.Indexes {

			rm.Indexes = append(rm.Indexes, &goFieldModel{
				FieldDescriptor: key,
			})
			fm.IndexCount++
		}

		// 联合索引字段不需要添加到Indexes中，它们会通过UnionIndexes单独处理

		fm.IndexedStructs = append(fm.IndexedStructs, &rm)

	}
}

func collectAllStructInfo(g *Globals, fm *goFileModel) {

	// 遍历所有类型
	for _, d := range g.FileDescriptor.Descriptors {

		// 这给被限制输出
		if !d.File.MatchTag(".go") {
			log.Infof("%s: %s", i18n.String(i18n.Printer_IgnoredByOutputTag), d.Name)
			continue
		}

		structM := &goStructModel{Descriptor: d}

		// 遍历字段
		for index, fd := range d.Fields {

			// 对CombineStruct的XXDefine对应的字段
			if d.Usage == model.DescriptorUsage_CombineStruct {

				// 这个字段被限制输出
				if fd.Complex != nil && !fd.Complex.File.MatchTag(".go") {
					continue
				}

				if fd.Complex != nil && fd.Complex.File.Pragma.GetBool("Vertical") {
					fm.VerticalFields = append(fm.VerticalFields, &goFieldModel{FieldDescriptor: fd})
				}
			}

			field := &goFieldModel{FieldDescriptor: fd}

			switch d.Kind {
			case model.DescriptorKind_Struct:
				field.Number = index + 1
			case model.DescriptorKind_Enum:
				field.Number = int(fd.EnumValue)
			}

			structM.GoFields = append(structM.GoFields, field)

		}

		switch d.Kind {
		case model.DescriptorKind_Struct:
			fm.Structs = append(fm.Structs, structM)
		case model.DescriptorKind_Enum:
			fm.Enums = append(fm.Enums, structM)
		}

	}
}

func (self *goPrinter) Run(g *Globals) *Stream {

	tpl, err := template.New("golang").Parse(goTemplate)
	if err != nil {
		log.Errorln(err)
		return nil
	}

	var fm goFileModel
	fm.ToolVersion = g.Version
	fm.FileDescriptor = g.FileDescriptor
	fm.PackageName = g.PackageName

	collectIndexInfo(g, &fm)
	collectAllStructInfo(g, &fm)

	// 收集所有结构体信息，包括没有索引的结构体
	for _, fd := range g.CombineStruct.Fields {
		if g.CombineStruct.Usage != model.DescriptorUsage_CombineStruct {
			continue
		}

		if fd.Complex == nil {
			continue
		}

		// 这个字段被限制输出
		if !fd.Complex.File.MatchTag(".go") {
			continue
		}

		// 这个结构有索引才创建
		fm.AllStructs = append(fm.AllStructs, &goIndexStructModel{FieldDescriptor: fd})
	}

	bf := NewStream()

	err = tpl.Execute(bf.Buffer(), &fm)
	if err != nil {
		log.Errorln(err)
		return nil
	}

	if err := formatCode(bf.Buffer()); err != nil {
		log.Errorln("format golang code err", err)
		log.Errorln(bf.Buffer().String())
		return nil
	}

	return bf
}

func formatCode(bf *bytes.Buffer) error {

	fset := token.NewFileSet()

	ast, err := parser.ParseFile(fset, "", bf, parser.ParseComments)
	if err != nil {
		return err
	}

	bf.Reset()

	err = (&printer.Config{Mode: printer.TabIndent | printer.UseSpaces, Tabwidth: 8}).Fprint(bf, fset, ast)
	if err != nil {
		return err
	}

	return nil
}

func init() {

	RegisterPrinter("go", &goPrinter{})

}
