package printer

import (
	"bytes"
	"fmt"
	"go/parser"
	"go/printer"
	"go/token"
	"text/template"

	"github.com/adamluo159/tabtoy/v2/i18n"
	"github.com/adamluo159/tabtoy/v2/model"
)

const goTemplate = `// Generated by github.com/adamluo159/tabtoy
// DO NOT EDIT!!
package {{.Package}}

import(
	"fmt"
	"encoding/json"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)
{{range $a, $en := .Enums}} 
// Defined in table: {{$en.DefinedTable}}
type {{$en.Name}} int32
const (	
{{range .GoFields}}{{if .Comment}}
	{{.Comment}}{{end}}
	{{$en.Name}}_{{.Name}} {{$en.Name}} = {{.Number}}
{{end}}
)
var (
{{$en.Name}}MapperValueByName = map[string]int32{ {{range .GoFields}}
	"{{.Name}}": {{.Number}}, {{end}}
}

{{$en.Name}}MapperNameByValue = map[int32]string{ {{range .GoFields}}
	{{.Number}}: "{{.Name}}" , {{end}}
}

{{$en.Name}}CommentByValue = map[int32]string{ {{range .GoFields}}
	{{.Number}}: "{{.RawComment}}" , {{end}}
}

)

func (self {{$en.Name}}) String() string {
	name, _ := {{$en.Name}}MapperNameByValue[int32(self)]
	return name
}
{{end}}

{{range $a, $strus := .Structs}} 
// Defined in table: {{$strus.DefinedTable}}
type {{$strus.Name}} struct{
	{{range $b, $fd := $strus.GoFields}}{{if .Comment}}
	{{.Comment}}{{end}}
	{{if .IsMap}}{{$fd.Name}} {{.MapTypeString}} {{$fd.StructTag}}{{else}}{{$fd.Name}} {{$fd.TypeString}} {{$fd.StructTag}}{{end}}
	{{end}}
}
{{end}}

// {{$.Name}} 访问接口
type {{$.Name}}Table struct{

	// 数据指针，使用原子操作进行更新
	data atomic.Pointer[{{$.Name}}Data]

	// 加载前回调
	preFuncList []func(*{{$.Name}}Table) error

	// 加载后回调
	postFuncList []func(*{{$.Name}}Table) error
}

// {{$.Name}} 数据结构体，用于写时复制
// 此结构体一旦创建，不应被修改
// 所有修改都通过创建新实例并原子替换data指针来实现
type {{$.Name}}Data struct{
	
	// 表格原始数据
	{{$.Name}}
	
	{{range $a, $strus := .IndexedStructs}} {{range .Indexes}}
{{if .IsOneToManyIndex}}{{$strus.Name}}By{{.Name}} map[{{.KeyType}}][]*{{$strus.TypeName}}
{{else}}{{$strus.Name}}By{{.Name}} map[{{.KeyType}}]*{{$strus.TypeName}}
{{end}}{{end}}{{end}}{{/* 联合索引字段定义 - 基于UnionIndex标记 */}}
{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}} map[struct{ K1 int32; K2 int32 }]*{{$strus.TypeName}}
{{end}}{{end}}{{end}}
}

{{range .VerticalFields}}
{{.Comment}}
func (self *{{$.Name}}Table) Get{{.Name}}( ) {{.ElementTypeString}} {
	return self.data.Load().{{.Name}}[0]
}
{{end}}

{{range .AllStructs}}
/** 获取{{.TypeName}}列表 */
func (self *{{$.Name}}Table) Get{{.TypeName}}s( ) []*{{.TypeName}} {
	return self.data.Load().{{.Name}}
}
{{end}}

{{range $strus := .IndexedStructs}} {{range .Indexes}}
/** 通过{{.Name}}获取{{$strus.TypeName}} */
{{if .IsOneToManyIndex}}
func (self *{{$.Name}}Table) Get{{$strus.TypeName}}By{{.Name}}(key {{.KeyType}}) []*{{$strus.TypeName}} {
	return self.data.Load().{{$strus.Name}}By{{.Name}}[key]
}
{{else}}
func (self *{{$.Name}}Table) Get{{$strus.TypeName}}By{{.Name}}(key {{.KeyType}}) *{{$strus.TypeName}} {
	return self.data.Load().{{$strus.Name}}By{{.Name}}[key]
}
{{end}}
{{end}}{{end}}{{/* 联合索引访问方法 - 基于UnionIndex标记 */}}
{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
/** 生成{{$strus.TypeName}}联合索引Key */
func Make{{$strus.TypeName}}Key{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}(k1 int32, k2 int32) struct{ K1 int32; K2 int32 } {
	return struct{ K1 int32; K2 int32 }{K1: k1, K2: k2}
}

/** 通过{{(index $unionFields 0).Name}}和{{(index $unionFields 1).Name}}获取{{$strus.TypeName}} */
func (self *{{$.Name}}Table) Get{{$strus.TypeName}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}(k1 int32, k2 int32) *{{$strus.TypeName}} {
	return self.data.Load().{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}[Make{{$strus.TypeName}}Key{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}}(k1, k2)]
}
{{end}}{{end}}{{end}}


// load{{$.Name}}StructItems 从json文件读取表单数据列表
func load{{$.Name}}StructItems[T any](filename string) ([]*T, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, fmt.Errorf("load %s failed: %w", filename, err)
	}

	var items []*T
	if err := json.Unmarshal(data, &items); err != nil {
		return nil, fmt.Errorf("unmarshal %s failed: %w", filename, err)
	}

	return items, nil
}

{{range $a, $strus := .IndexedStructs}}
// build{{$strus.Name}}Indexes 重建{{$strus.Name}}的所有索引映射
// 每次调用创建全新的map并填充, 保证与其他数据实例不共享引用
func (self *{{$.Name}}Data) build{{$strus.Name}}Indexes() error {
	{{range .Indexes}}
	{{if .IsOneToManyIndex}}self.{{$strus.Name}}By{{.Name}} = make(map[{{.KeyType}}][]*{{$strus.TypeName}})
	{{else}}self.{{$strus.Name}}By{{.Name}} = make(map[{{.KeyType}}]*{{$strus.TypeName}})
	{{end}}{{end}}{{/* 联合索引初始化 - 基于UnionIndex标记 */}}
	{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
	self.{{$strus.Name}}By{{(index $unionFields 0).Name}}{{(index $unionFields 1).Name}} = make(map[struct{ K1 int32; K2 int32 }]*{{$strus.TypeName}})
	{{end}}{{end}}

	for _, def := range self.{{$strus.Name}} {
		{{range .Indexes}}
		{{if .IsOneToManyIndex}}
		// 一对多索引：允许重复key
		self.{{$strus.Name}}By{{.Name}}[def.{{.Name}}] = append(self.{{$strus.Name}}By{{.Name}}[def.{{.Name}}], def)
		{{else}}
		// 一对一索引：不允许重复key
		if _, ok := self.{{$strus.Name}}By{{.Name}}[def.{{.Name}}]; ok {
			return fmt.Errorf("duplicate index in {{$strus.Name}}By{{.Name}}: %v", def.{{.Name}})
		}
		self.{{$strus.Name}}By{{.Name}}[def.{{.Name}}] = def
		{{end}}
		{{end}}
		{{/* 联合索引构建逻辑 - 基于UnionIndex标记 */}}
		{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}
		{{if gt (len $unionFields) 1}}
		{{$idx1 := index $unionFields 0}}
		{{$idx2 := index $unionFields 1}}
		key := struct{ K1 int32; K2 int32 }{K1: def.{{$idx1.Name}}, K2: def.{{$idx2.Name}}}
		if _, ok := self.{{$strus.Name}}By{{$idx1.Name}}{{$idx2.Name}}[key]; ok {
			return fmt.Errorf("duplicate index in {{$strus.Name}}By{{$idx1.Name}}{{$idx2.Name}}: %v", key)
		}
		self.{{$strus.Name}}By{{$idx1.Name}}{{$idx2.Name}}[key] = def
		{{end}}
		{{end}}
	}

	return nil
}
{{end}}
// buildIndexes 基于原始数据重建所有索引映射
func (self *{{$.Name}}Data) buildIndexes() error {
	{{range $a, $strus := .IndexedStructs}}
	if err := self.build{{$strus.Name}}Indexes(); err != nil {
		return err
	}
	{{end}}
	return nil
}

// 从json文件加载
func (self *{{$.Name}}Table) Load(filename string) error {
	data, err := os.ReadFile(filename)

	if err != nil {
		return err
	}

	return self.LoadData(data)
}

// 从目录加载拆分的json文件
func (self *{{$.Name}}Table) LoadFromDir(dir string) error {
	// 创建新的数据实例
	newData := &{{$.Name}}Data{}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err := v(self); err != nil {
			return err
		}
	}

	// 加载每个表单的json文件
	{{range $a, $strus := .AllStructs}}
	{
		items, err := load{{$.Name}}StructItems[{{$strus.TypeName}}](filepath.Join(dir, "{{$strus.Name}}.json"))
		if err != nil {
			return err
		}
		newData.{{$strus.Name}} = items
	}
	{{end}}

	// 生成索引
	if err := newData.buildIndexes(); err != nil {
		return err
	}

	// 原子替换数据指针
	self.data.Store(newData)

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err := v(self); err != nil {
			return err
		}
	}

	return nil
}

// ReloadFile 从单个json文件重新加载对应表单(热重载)
// filename 为目录下的json文件路径, 按文件名匹配表单, 如 dir/A.json -> 表单A
// 仅重载该表单的数据并重建该表单的索引, 其他表单的数据和索引与旧数据共享引用(旧数据不可变, 并发读安全)
// 通过原子替换数据指针对外不可见中间状态
func (self *{{$.Name}}Table) ReloadFile(filename string) error {
	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err := v(self); err != nil {
			return err
		}
	}

	// 提取文件名(不含目录和后缀)作为表单名, 如 dir/A.json -> A
	name := strings.TrimSuffix(filepath.Base(filename), filepath.Ext(filename))

	// 写时复制: 基于当前数据浅拷贝, 未重载的表单共享原切片引用
	oldData := self.data.Load()
	if oldData == nil {
		return fmt.Errorf("{{$.Name}} table data not initialized")
	}
	newData := *oldData

	switch name {
	{{range $a, $strus := .AllStructs}}
	case "{{$strus.Name}}":
		items, err := load{{$.Name}}StructItems[{{$strus.TypeName}}](filename)
		if err != nil {
			return err
		}
		newData.{{$strus.Name}} = items
	{{end}}
	default:
		return fmt.Errorf("unknown table file: %s", filename)
	}

	// 仅重建该表单的索引(全新map), 其他表单索引共享旧数据实例的map
	{{range $a, $strus := .IndexedStructs}}
	if name == "{{$strus.Name}}" {
		if err := newData.build{{$strus.Name}}Indexes(); err != nil {
			return err
		}
	}
	{{end}}

	// 原子替换数据指针, 完成热重载
	self.data.Store(&newData)

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err := v(self); err != nil {
			return err
		}
	}

	return nil
}

// StartWatchDir 启动定时热更新: 每隔interval检查dir下json文件的修改时间
// 有更新的文件自动调用ReloadFile重载(仅重载变化的文件), 新增的json文件同样会被加载
// 首次扫描只记录修改时间基准, 不触发重载; 重载失败时调用onError(可为nil), 下次检查自动重试
// 每次扫描的变更文件列表及重载耗时通过标准log输出, 无变更的扫描不产生日志
// 返回停止监视的函数
func (self *{{$.Name}}Table) StartWatchDir(dir string, interval time.Duration, onError func(error)) (stop func()) {
	modTimes := make(map[string]time.Time)
	ticker := time.NewTicker(interval)
	done := make(chan struct{})

	scan := func() {
		scanStart := time.Now()
		entries, err := os.ReadDir(dir)
		if err != nil {
			log.Printf("[{{$.Name}}Table.WatchDir] scan %s failed: %v", dir, err)
			if onError != nil {
				onError(err)
			}
			return
		}

		// 第一阶段: 收集本次扫描发现的变更文件(修改时间有更新, 含新增json文件)
		changed := make([]struct {
			name    string
			modTime time.Time
		}, 0, len(entries))

		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
				continue
			}

			info, err := entry.Info()
			if err != nil {
				if onError != nil {
					onError(err)
				}
				continue
			}

			name := entry.Name()
			last, ok := modTimes[name]
			if !ok {
				// 首次发现该文件, 只记录修改时间基准
				modTimes[name] = info.ModTime()
				continue
			}

			if info.ModTime().After(last) {
				changed = append(changed, struct {
					name    string
					modTime time.Time
				}{name: name, modTime: info.ModTime()})
			}
		}

		if len(changed) == 0 {
			return
		}

		names := make([]string, 0, len(changed))
		for _, c := range changed {
			names = append(names, c.name)
		}
		log.Printf("[{{$.Name}}Table.WatchDir] scan %s: %d file(s) changed: %v (scan cost %s)", dir, len(changed), names, time.Since(scanStart))

		// 第二阶段: 逐个重载并记录耗时, 重载成功才更新基准(失败下次自动重试)
		reloadStart := time.Now()
		for _, c := range changed {
			fileStart := time.Now()
			if err := self.ReloadFile(filepath.Join(dir, c.name)); err != nil {
				log.Printf("[{{$.Name}}Table.WatchDir] reload %s failed (cost %s): %v", c.name, time.Since(fileStart), err)
				if onError != nil {
					onError(err)
				}
				continue
			}
			modTimes[c.name] = c.modTime
			log.Printf("[{{$.Name}}Table.WatchDir] reload %s ok (cost %s)", c.name, time.Since(fileStart))
		}
		log.Printf("[{{$.Name}}Table.WatchDir] reload finished: %d file(s), total cost %s", len(changed), time.Since(reloadStart))
	}

	go func() {
		log.Printf("[{{$.Name}}Table.WatchDir] watching %s every %s", dir, interval)
		scan()
		log.Printf("[{{$.Name}}Table.WatchDir] baseline established: %d json file(s) in %s", len(modTimes), dir)
		for {
			select {
			case <-ticker.C:
				scan()
			case <-done:
				ticker.Stop()
				return
			}
		}
	}()

	var once sync.Once
	return func() {
		once.Do(func() {
			log.Printf("[{{$.Name}}Table.WatchDir] stop watching %s", dir)
			close(done)
		})
	}
}

// 从二进制加载
func (self *{{$.Name}}Table) LoadData(data []byte) error {
	var newTab {{$.Name}}

	// 读取
	err := json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 创建新的数据实例
	newData := &{{$.Name}}Data{
		{{$.Name}}: newTab,
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 生成索引
	if err = newData.buildIndexes(); err != nil {
		return err
	}

	// 原子替换数据指针
	self.data.Store(newData)

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册加载前回调
func (self *{{$.Name}}Table) RegisterPreEntry(callback func(*{{$.Name}}Table) error) {
	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *{{$.Name}}Table) RegisterPostEntry(callback func(*{{$.Name}}Table) error) {
	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个{{$.Name}}表读取实例
func New{{$.Name}}Table() *{{$.Name}}Table {
	// 创建初始数据实例(空数据+空索引)
	initialData := &{{$.Name}}Data{}
	_ = initialData.buildIndexes()

	table := &{{$.Name}}Table{}

	// 原子存储初始数据
	table.data.Store(initialData)

	return table
}
`

// 每个带有MakeIndex的列
type goFieldModel struct {
	*model.FieldDescriptor
	Number int
}

func (self *goFieldModel) Alias() string {
	return self.FieldDescriptor.Meta.GetString("Alias")
}

// IsOneToManyIndex 判断是否是一对多索引（只有MakeIndex没有RepeatCheck）
func (self *goFieldModel) IsOneToManyIndex() bool {
	return self.Meta.GetBool("MakeIndex") && !self.Meta.GetBool("RepeatCheck")
}

func (self *goFieldModel) RawComment() string {
	var out string

	if self.FieldDescriptor.Meta.GetString("Alias") != "" {
		return self.FieldDescriptor.Meta.GetString("Alias")
	}

	if self.FieldDescriptor.Comment != "" {
		return self.FieldDescriptor.Comment
	}
	return out
}

func (self *goFieldModel) Comment() string {

	var out string

	if self.FieldDescriptor.Comment != "" {
		return "//" + self.FieldDescriptor.Comment
	}

	if self.FieldDescriptor.Meta.GetString("Alias") != "" {
		return "//" + self.FieldDescriptor.Meta.GetString("Alias")
	}

	return out

}

func (self *goFieldModel) KeyType() string {

	// 修复: 当枚举做索引时, 多出包名
	if self.Type == model.FieldType_Enum {
		return self.Complex.Name
	}

	return model.FieldTypeToString(self.Type)
}

func (self *goFieldModel) StructTag() string {

	var buf bytes.Buffer

	buf.WriteString("`")

	var userTagCount int

	self.Meta.VisitUserMeta(func(k string, v interface{}) bool {

		if userTagCount > 0 {
			buf.WriteString(" ")
		}

		buf.WriteString(fmt.Sprintf("%s:\"%s\"", k, v))

		userTagCount++

		return true
	})

	buf.WriteString("`")

	if userTagCount == 0 {
		return ""
	}

	return buf.String()
}

func (self *goFieldModel) ElementTypeString() string {

	switch self.FieldDescriptor.Type {
	case model.FieldType_Float:
		return "float32"
	case model.FieldType_Struct:
		return "*" + self.FieldDescriptor.TypeString()
	default:
		return self.FieldDescriptor.TypeString()
	}
}

func (self *goFieldModel) TypeString() string {

	var prefix string
	if self.IsRepeated {
		prefix = "[]"
	}

	return prefix + self.ElementTypeString()

}

func (self *goFieldModel) IsMap() bool {
	return self.FieldDescriptor.Type == model.FieldType_Map
}

func (self *goFieldModel) MapKeyGoType() string {
	if self.FieldDescriptor.MapKeyType == model.FieldType_Enum {
		if self.FieldDescriptor.MapKeyComplex != nil {
			return self.FieldDescriptor.MapKeyComplex.Name
		}
	}
	return model.FieldTypeToString(self.FieldDescriptor.MapKeyType)
}

func (self *goFieldModel) MapValueGoType() string {
	switch self.FieldDescriptor.MapValueType {
	case model.FieldType_Struct:
		if self.FieldDescriptor.MapValueComplex != nil {
			return "*" + self.FieldDescriptor.MapValueComplex.Name
		}
	case model.FieldType_Enum:
		if self.FieldDescriptor.MapValueComplex != nil {
			return self.FieldDescriptor.MapValueComplex.Name
		}
	default:
		return model.FieldTypeToString(self.FieldDescriptor.MapValueType)
	}
	return model.FieldTypeToString(self.FieldDescriptor.MapValueType)
}

func (self *goFieldModel) MapTypeString() string {
	return "map[" + self.MapKeyGoType() + "]" + self.MapValueGoType()
}

// 对应每个电子表格文件
type goIndexStructModel struct {
	*model.FieldDescriptor

	Indexes []*goFieldModel
}

func (self *goIndexStructModel) TypeName() string {
	return self.Complex.Name
}

type goStructModel struct {
	*model.Descriptor

	GoFields []*goFieldModel
}

func (self *goStructModel) DefinedTable() string {
	return self.File.Name
}

// 整个导出文件
type goFileModel struct {
	*model.FileDescriptor
	ToolVersion    string
	IndexedStructs []*goIndexStructModel
	Structs        []*goStructModel
	Enums          []*goStructModel
	AllStructs     []*goIndexStructModel
	PackageName    string

	// 配置的字段
	VerticalFields []*goFieldModel
}

func (self *goFileModel) HasAnyStruct() bool {
	return len(self.Structs) > 0
}

func (self *goFileModel) Package() string {
	// 优先使用命令行指定的包名，如果没有则使用表格中定义的包名
	if self.PackageName != "" {
		return self.PackageName
	}
	return self.FileDescriptor.Pragma.GetString("Package")
}

type goPrinter struct {
}

func collectIndexInfo(g *Globals, fm *goFileModel) {

	// 遍历需要导出的合并字段
	for _, fd := range g.CombineStruct.Fields {

		// fd --> 对应每个文件的Row定义, 也就是XXDefine, 在CombineStruct上, 只是一个字段

		// 对CombineStruct的XXDefine对应的字段
		if g.CombineStruct.Usage != model.DescriptorUsage_CombineStruct {
			continue
		}

		//非结构体不输出(其实根本不会击中)
		if fd.Complex == nil {
			continue
		}

		// 这个字段被限制输出
		if !fd.Complex.File.MatchTag(".go") {
			continue
		}

		// 这个结构有索引或联合索引才创建
		if len(fd.Complex.Indexes) == 0 && len(fd.Complex.UnionIndexes) == 0 {
			continue
		}

		rm := goIndexStructModel{
			FieldDescriptor: fd,
		}

		// 只收集单个索引字段，联合索引字段不生成单独索引
		for _, key := range fd.Complex.Indexes {

			rm.Indexes = append(rm.Indexes, &goFieldModel{
				FieldDescriptor: key,
			})
		}

		// 联合索引字段不需要添加到Indexes中，它们会通过UnionIndexes单独处理

		fm.IndexedStructs = append(fm.IndexedStructs, &rm)

	}
}

func collectAllStructInfo(g *Globals, fm *goFileModel) {

	// 遍历所有类型
	for _, d := range g.FileDescriptor.Descriptors {

		// 这给被限制输出
		if !d.File.MatchTag(".go") {
			log.Infof("%s: %s", i18n.String(i18n.Printer_IgnoredByOutputTag), d.Name)
			continue
		}

		structM := &goStructModel{Descriptor: d}

		// 遍历字段
		for index, fd := range d.Fields {

			// 对CombineStruct的XXDefine对应的字段
			if d.Usage == model.DescriptorUsage_CombineStruct {

				// 这个字段被限制输出
				if fd.Complex != nil && !fd.Complex.File.MatchTag(".go") {
					continue
				}

				if fd.Complex != nil && fd.Complex.File.Pragma.GetBool("Vertical") {
					fm.VerticalFields = append(fm.VerticalFields, &goFieldModel{FieldDescriptor: fd})
				}
			}

			field := &goFieldModel{FieldDescriptor: fd}

			switch d.Kind {
			case model.DescriptorKind_Struct:
				field.Number = index + 1
			case model.DescriptorKind_Enum:
				field.Number = int(fd.EnumValue)
			}

			structM.GoFields = append(structM.GoFields, field)

		}

		switch d.Kind {
		case model.DescriptorKind_Struct:
			fm.Structs = append(fm.Structs, structM)
		case model.DescriptorKind_Enum:
			fm.Enums = append(fm.Enums, structM)
		}

	}
}

func (self *goPrinter) Run(g *Globals) *Stream {

	tpl, err := template.New("golang").Parse(goTemplate)
	if err != nil {
		log.Errorln(err)
		return nil
	}

	var fm goFileModel
	fm.ToolVersion = g.Version
	fm.FileDescriptor = g.FileDescriptor
	fm.PackageName = g.PackageName

	collectIndexInfo(g, &fm)
	collectAllStructInfo(g, &fm)

	// 收集所有结构体信息，包括没有索引的结构体
	for _, fd := range g.CombineStruct.Fields {
		if g.CombineStruct.Usage != model.DescriptorUsage_CombineStruct {
			continue
		}

		if fd.Complex == nil {
			continue
		}

		// 这个字段被限制输出
		if !fd.Complex.File.MatchTag(".go") {
			continue
		}

		// 这个结构有索引才创建
		fm.AllStructs = append(fm.AllStructs, &goIndexStructModel{FieldDescriptor: fd})
	}

	bf := NewStream()

	err = tpl.Execute(bf.Buffer(), &fm)
	if err != nil {
		log.Errorln(err)
		return nil
	}

	if err := formatCode(bf.Buffer()); err != nil {
		log.Errorln("format golang code err", err)
		log.Errorln(bf.Buffer().String())
		return nil
	}

	return bf
}

func formatCode(bf *bytes.Buffer) error {

	fset := token.NewFileSet()

	ast, err := parser.ParseFile(fset, "", bf, parser.ParseComments)
	if err != nil {
		return err
	}

	bf.Reset()

	err = (&printer.Config{Mode: printer.TabIndent | printer.UseSpaces, Tabwidth: 8}).Fprint(bf, fset, ast)
	if err != nil {
		return err
	}

	return nil
}

func init() {

	RegisterPrinter("go", &goPrinter{})

}
