package printer

import (
	"text/template"

	"github.com/adamluo159/tabtoy/v2/model"
)

const tsTemplate = "// Generated by github.com/adamluo159/tabtoy\n" +
	"// Version: {{.ToolVersion}}\n" +
	"// DO NOT EDIT!!\n" +
	"export namespace config {\n" +
	"{{range $a, $en := .Enums}}\n" +
	"/** 定义于表格: {{$en.DefinedTable}} */\n" +
	"export enum {{$en.Name}} {\n" +
	"{{range .TSFields}}    /** {{.Comment}} */\n" +
	"    {{.Name}} = {{.Number}},\n" +
	"{{end}}}\n" +
	"\n" +
	"export const {{$en.Name}}Mapper = {\n" +
	"{{range .TSFields}}    {{.Number}}: \"{{.Name}}\",\n" +
	"{{end}}} as const;\n" +
	"\n" +
	"export const {{$en.Name}}ReverseMapper = {\n" +
	"{{range .TSFields}}    \"{{.Name}}\": {{.Number}},\n" +
	"{{end}}} as const;\n" +
	"\n" +
	"export type {{$en.Name}}Type = keyof typeof {{$en.Name}}ReverseMapper;\n" +
	"export type {{$en.Name}}Value = typeof {{$en.Name}}Mapper[keyof typeof {{$en.Name}}Mapper];\n" +
	"{{end}}\n" +
	"\n" +
	"{{range $a, $strus := .Structs}}\n" +
	"/** 定义于表格: {{$strus.DefinedTable}} */\n" +
	"export interface {{$strus.Name}} {\n" +
	"{{range $b, $fd := $strus.TSFields}}    /** {{.Comment}} */\n" +
	"    {{.Name}}{{if not .Required}}?{{end}}: {{.TypeString}};\n" +
	"{{end}}}\n" +
	"{{end}}\n" +
	"\n" +
	"/** 表格分片数据结构 */\n" +
	"export interface {{$.Name}}TablePart {\n" +
	"{{range $a, $strus := .All}}    {{$strus.Name}}?: {{$strus.TypeString}}[];\n" +
	"{{end}}}\n" +
	"\n" +
	"/** {{$.Name}}表格访问器 */\n" +
	"export class {{$.Name}}TableAccessor {\n" +
	"    private data: {{$.Name}}Table;\n" +
	"\n" +
	"{{range $a, $strus := .IndexedStructs}}{{range .Indexes}}    private {{$strus.Name}}By{{.Name}} = new Map<{{.KeyType}}, {{$strus.TypeName}}>();\n" +
	"{{end}}{{end}}\n" +
	"\n" +
	"    /** 从JSON字符串加载 */\n" +
	"    loadFromString(data: string): boolean {\n" +
	"        try {\n" +
	"            const parsed = JSON.parse(data) as {{$.Name}}Table;\n" +
	"            this.data = parsed;\n" +
	"            this.buildAllIndexes();\n" +
	"            return true;\n" +
	"        } catch (e) {\n" +
	"            return false;\n" +
	"        }\n" +
	"    }\n" +
	"\n" +
	"    /** 从字符串额外加载分片数据 */\n" +
	"    addLoadPartFromString(data: string): void {\n" +
	"        try {\n" +
	"            const part = JSON.parse(data) as {{$.Name}}TablePart;\n" +       
	"            {{range $a, $strus := .All}}\n" +
	"            if (part.{{$strus.Name}}) {\n" +
	"                this.data.{{$strus.Name}}.push(...part.{{$strus.Name}});\n" +
	"                {{if $strus.HasAnyIndex}}this.build{{$strus.Name}}Indexes();{{end}}\n" +
	"            }\n" +
	"            {{end}}\n" +                   
	"        } catch (e) {\n" +
	"            throw new Error(\"Failed to add part \" + data + \": \" + (e as Error).message);\n" +
	"        }\n" +
	"    }\n"+
	"    /** 构建所有索引 */\n" +
	"    private buildAllIndexes() {\n" +
	"        {{range $a, $strus := .IndexedStructs}}this.build{{$strus.Name}}Indexes();\n" +
	"        {{end}}}\n" +
	"{{range $a, $strus := .IndexedStructs}}\n" +
	"    /** 构建{{$strus.Name}}索引 */\n" +
	"    private build{{$strus.Name}}Indexes() {\n" +
	"        {{range .Indexes}}this.{{$strus.Name}}By{{.Name}}.clear();\n" +
	"        {{end}}\n" +
	"        for (const item of this.data.{{$strus.Name}}) {\n" +
	"            {{range .Indexes}}if (this.{{$strus.Name}}By{{.Name}}.has(item.{{.Name}})) {\n" +
	"                throw new Error(\"Duplicate index in {{$strus.Name}}By{{.Name}}: \" + item.{{.Name}});\n" +
	"            }\n" +
	"            this.{{$strus.Name}}By{{.Name}}.set(item.{{.Name}}, item);\n" +
	"            {{end}}}\n" +
	"    }\n" +
	"{{end}}\n" +
	"{{range $a, $strus := .IndexedStructs}}{{range .Indexes}}\n" +
	"    /** 通过{{.Name}}获取{{$strus.Name}} */\n" +
	"    get{{$strus.Name}}By{{.Name}}(key: {{.KeyType}}): {{$strus.TypeName}} | undefined {\n" +
	"        return this.{{$strus.Name}}By{{.Name}}.get(key);\n" +
	"    }\n" +
	"{{end}}{{end}}\n" +
	"{{range $a, $strus := .All}}\n" +
	"    /**获取{{$strus.Name}} */" +
	"    {{if .IsVertical}}\n" +
	"    get{{$strus.Name}}(): {{$strus.TypeString}} {\n" +
	"        return this.data.{{$strus.Name}}[0];\n" +
	"    }" +
	"    {{else}}\n" +
	"    get{{$strus.Name}}s(): {{$strus.TypeString}}[] {\n" +
	"        return this.data.{{$strus.Name}};\n" +
	"    }" +
	"    {{end}}\n" +
	"{{end}}}}\n"

// TypeScript 字段模型
type tsFieldModel struct {
	*model.FieldDescriptor
	Number   int
	Required bool
}

func (self *tsFieldModel) Comment() string {
	if self.FieldDescriptor.Comment != "" {
		return self.FieldDescriptor.Comment
	}
	if alias := self.FieldDescriptor.Meta.GetString("Alias"); alias != "" {
		return alias
	}
	return ""
}

func (self *tsFieldModel) KeyType() string {
	switch self.Type {
	case model.FieldType_Enum:
		return self.Complex.Name
	case model.FieldType_Int32:
		return "number"
	case model.FieldType_String:
		return "string"
	default:
		return model.FieldTypeToString(self.Type)
	}
}

func (self *tsFieldModel) ElementTypeString() string {
	switch self.Type {
	case model.FieldType_Enum:
		return self.Complex.Name
	case model.FieldType_Struct:
		return self.Complex.Name
	case model.FieldType_Float:
		return "number"
	case model.FieldType_Int32:
		return "number"
	case model.FieldType_String:
		return "string"
	case model.FieldType_Bool:
		return "boolean"
	default:
		return "any"
	}
}

func (self *tsFieldModel) TypeString() string {
	if self.IsRepeated {
		return self.ElementTypeString() + "[]"
	}
	return self.ElementTypeString()
}

// TypeScript 索引结构模型
type tsIndexedStructModel struct {
	*model.FieldDescriptor
	Indexes    []*tsFieldModel
	IsVertical bool
}

func (self *tsIndexedStructModel) TypeName() string {
	return self.Complex.Name
}
func (self *tsIndexedStructModel) HasAnyIndex() bool {
	return len(self.FieldDescriptor.Complex.Indexes) > 0
}

// TypeScript 结构体模型
type tsStructModel struct {
	*model.Descriptor
	TSFields []*tsFieldModel
}

func (self *tsStructModel) DefinedTable() string {
	return self.File.Name
}

// TypeScript 文件模型
type tsFileModel struct {
	*model.FileDescriptor
	ToolVersion    string
	IndexedStructs []*tsIndexedStructModel
	All            []*tsIndexedStructModel
	Structs        []*tsStructModel
	Enums          []*tsStructModel
	Verticals      []*tsIndexedStructModel
	Name           string
}

func (self *tsFileModel) Package() string {
	return self.FileDescriptor.Pragma.GetString("Package")
}

// 收集索引信息
func collectTSIndexInfo(g *Globals, fm *tsFileModel) {
	for _, fd := range g.CombineStruct.Fields {
		if g.CombineStruct.Usage != model.DescriptorUsage_CombineStruct {
			continue
		}

		if fd.Complex == nil {
			continue
		}

		if !fd.Complex.File.MatchTag(".ts") {
			continue
		}

		// if fd.Complex.File.Pragma.GetBool("Vertical") {
		// 	fm.Verticals = append(fm.Verticals, &tsIndexedStructModel{FieldDescriptor: fd})
		// 	continue
		// }

		fm.All = append(fm.All, &tsIndexedStructModel{
			FieldDescriptor: fd,
			IsVertical:      fd.Complex.File.Pragma.GetBool("Vertical"), 
		})
		if len(fd.Complex.Indexes) == 0 {
			continue
		}

		rm := tsIndexedStructModel{FieldDescriptor: fd}

		for _, key := range fd.Complex.Indexes {
			rm.Indexes = append(rm.Indexes, &tsFieldModel{
				FieldDescriptor: key,
			})
		}

		fm.IndexedStructs = append(fm.IndexedStructs, &rm)
	}
}

// 收集所有结构信息
func collectAllTSStructInfo(g *Globals, fm *tsFileModel) {
	for _, d := range g.FileDescriptor.Descriptors {
		if !d.File.MatchTag(".ts") {
			continue
		}

		structM := &tsStructModel{Descriptor: d}

		for index, fd := range d.Fields {
			field := &tsFieldModel{
				FieldDescriptor: fd,
				Required:        !fd.Meta.GetBool("Optional"),
			}

			switch d.Kind {
			case model.DescriptorKind_Struct:
				field.Number = index + 1
			case model.DescriptorKind_Enum:
				field.Number = int(fd.EnumValue)
			}

			structM.TSFields = append(structM.TSFields, field)
		}

		switch d.Kind {
		case model.DescriptorKind_Struct:
			fm.Structs = append(fm.Structs, structM)
		case model.DescriptorKind_Enum:
			fm.Enums = append(fm.Enums, structM)
		}
	}
}

// TypeScript 打印机
type tsPrinter struct{}

func (self *tsPrinter) Run(g *Globals) *Stream {
	tpl, err := template.New("typescript").Parse(tsTemplate)
	if err != nil {
		log.Errorln("parse typescript template failed:", err)
		return nil
	}

	var fm tsFileModel
	fm.ToolVersion = g.Version
	fm.FileDescriptor = g.FileDescriptor
	fm.Name = g.FileDescriptor.Pragma.GetString("TableName")

	collectTSIndexInfo(g, &fm)
	collectAllTSStructInfo(g, &fm)

	bf := NewStream()
	err = tpl.Execute(bf.Buffer(), &fm)
	if err != nil {
		log.Errorln("execute template failed:", err)
		return nil
	}

	return bf
}

func init() {
	RegisterPrinter("ts", &tsPrinter{})
}
