package printer

import (
	"text/template"

	"github.com/adamluo159/tabtoy/v2/model"
)

// 修改TypeScript模板文件
const tsTemplate = `// Generated by github.com/adamluo159/tabtoy
// Version: {{.ToolVersion}}
// DO NOT EDIT!!
export namespace config {

{{range $a, $en := .Enums}}

/** 定义于表格: {{$en.DefinedTable}} */
export enum {{$en.Name}} {
{{range .TSFields}}    /** {{.Comment}} */
    {{.Name}} = {{.Number}},
{{end}}}

export const {{$en.Name}}Mapper = {
{{range .TSFields}}    {{.Number}}: "{{.Name}}",
{{end}}} as const;

export const {{$en.Name}}ReverseMapper = {
{{range .TSFields}}    "{{.Name}}": {{.Number}},
{{end}}} as const;

export type {{$en.Name}}Type = keyof typeof {{$en.Name}}ReverseMapper;
export type {{$en.Name}}Value = typeof {{$en.Name}}Mapper[keyof typeof {{$en.Name}}Mapper];
{{end}}

{{range $a, $strus := .Structs}}

/** 定义于表格: {{$strus.DefinedTable}} */
export interface {{$strus.Name}} {
{{range $b, $fd := $strus.TSFields}}    /** {{.Comment}} */
    {{.Name}}{{if not .Required}}?{{end}}: {{.TypeString}};
{{end}}}
{{end}}

/** 表格分片数据结构 */
export interface TablePart {
{{range $a, $strus := .All}}    {{$strus.Name}}?: {{$strus.TypeString}}[];
{{end}}
}

{{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
/** 生成{{$strus.TypeName}}联合索引Key */
export function make{{$strus.TypeName}}Key{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}({{range $i, $field := $unionFields}}{{if $i}}, {{end}}key{{add $i 1}}: number{{end}}): string {
    return {{range $i, $field := $unionFields}}{{if $i}} + "|" + {{end}}key{{add $i 1}}{{end}};
}
{{end}}{{end}}{{end}}

/** 表格访问器 */
export class TableAccessor {
    private data: Table;

    {{range $a, $strus := .IndexedStructs}} {{range .Indexes}}
    private {{$strus.TypeName}}By{{.Name}} = new Map<{{.KeyType}}, {{$strus.TypeName}}>();
    {{end}}{{end}}{{/* 联合索引字段定义 - 基于UnionIndex标记 */}}
    {{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
    private {{$strus.TypeName}}By{{range $i, $field := $unionFields}}{{$field.Name}}{{end}} = new Map<string, {{$strus.TypeName}}>();
    {{end}}{{end}}{{end}}

    /** 构造函数 */
    constructor() {
        this.data = {
            {{range $a, $strus := .All}}
            {{$strus.Name}}: [],
            {{end}}
        };
    }

    /** 从JSON字符串加载 */
    loadFromString(data: string): boolean {
        try {
            const parsed = JSON.parse(data) as Table;
            this.data = parsed;
            this.buildAllIndexes();
            return true;
        } catch (e) {
            return false;
        }
    }

    /** 从JSON字符串加载指定表 */
    loadTableByName(tableName: string, data: string): boolean {
        try {
            switch (tableName) {
                {{range $a, $strus := .All}}
                case "{{$strus.Name}}":
                    this.data.{{$strus.Name}} = JSON.parse(data) as {{$strus.TypeName}}[];
                    {{if or (gt (len $strus.Indexes) 0) (gt (len $strus.Complex.UnionIndexes) 0)}}
                    this.build{{$strus.TypeName}}Indexes();
                    {{end}}
                    break;
                {{end}}
                default:
                    return false;
            }
            return true;
        } catch (e) {
            return false;
        }
    }
    /** 构建所有索引 */
    private buildAllIndexes() {
        {{range $a, $strus := .IndexedStructs}}
        this.build{{$strus.TypeName}}Indexes();
        {{end}}
    }

    {{range $a, $strus := .IndexedStructs}}
    /** 构建{{$strus.TypeName}}索引 */
    private build{{$strus.TypeName}}Indexes() {
        {{range .Indexes}}
        this.{{$strus.TypeName}}By{{.Name}}.clear();
        {{end}}
        {{/* 联合索引清除 */}}
        {{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
        this.{{$strus.TypeName}}By{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}.clear();
        {{end}}{{end}}
        
        for (const item of this.data.{{$strus.Name}}) {
            {{range .Indexes}}
            if (this.{{$strus.TypeName}}By{{.Name}}.has(item.{{.Name}})) {
                throw new Error("Duplicate index in {{$strus.TypeName}}By{{.Name}}: " + item.{{.Name}});
            }
            this.{{$strus.TypeName}}By{{.Name}}.set(item.{{.Name}}, item);
            {{end}}
            {{/* 联合索引构建 */}}
            {{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
            const combinedKey = {{range $i, $field := $unionFields}}{{if $i}} + "|" + {{end}}item.{{$field.Name}}{{end}};
            if (this.{{$strus.TypeName}}By{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}.has(combinedKey)) {
                throw new Error("Duplicate combined index in {{$strus.TypeName}}By{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}: " + combinedKey);
            }
            this.{{$strus.TypeName}}By{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}.set(combinedKey, item);
            {{end}}{{end}}
        }
    }
    {{end}}

    {{range $a, $strus := .IndexedStructs}} {{range .Indexes}}
    /** 通过{{.Name}}获取{{$strus.TypeName}} */
    get{{$strus.TypeName}}By{{.Name}}(key: {{.KeyType}}): {{$strus.TypeName}} | undefined {
        return this.{{$strus.TypeName}}By{{.Name}}.get(key);
    }
    {{end}}{{end}}{{/* 联合索引访问方法 - 基于UnionIndex标记 */}}
    {{range $a, $strus := .IndexedStructs}}{{range $unionName, $unionFields := $strus.Complex.UnionIndexes}}{{if gt (len $unionFields) 1}}
    /** 通过{{range $i, $field := $unionFields}}{{if $i}}和{{end}}{{$field.Name}}{{end}}获取{{$strus.TypeName}} */
    get{{$strus.TypeName}}By{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}({{range $i, $field := $unionFields}}{{if $i}}, {{end}}key{{add $i 1}}: number{{end}}): {{$strus.TypeName}} | undefined {
        const combinedKey = make{{$strus.TypeName}}Key{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}({{range $i, $field := $unionFields}}{{if $i}}, {{end}}key{{add $i 1}}{{end}});
        return this.{{$strus.TypeName}}By{{range $i, $field := $unionFields}}{{$field.Name}}{{end}}.get(combinedKey);
    }
    {{end}}{{end}}{{end}}

    {{range $a, $strus := .All}}{{if not $strus.IsVertical}}
    /**获取{{$strus.TypeName}}列表 */    
    get{{$strus.TypeName}}s(): {{$strus.TypeName}}[] {
        return this.data.{{$strus.Name}};
    }    
    {{end}}{{end}}
    {{range $a, $strus := .All}}{{if $strus.IsVertical}}
    /**获取{{$strus.TypeName}}配置 */    
    get{{$strus.TypeName}}(): {{$strus.TypeName}} {
        return this.data.{{$strus.Name}}[0];
    }    
    {{end}}{{end}} 
  }  
}`

// TypeScript 字段模型
type tsFieldModel struct {
	*model.FieldDescriptor
	Number   int
	Required bool
}

func (self *tsFieldModel) Comment() string {
	if self.FieldDescriptor.Comment != "" {
		return self.FieldDescriptor.Comment
	}
	if alias := self.FieldDescriptor.Meta.GetString("Alias"); alias != "" {
		return alias
	}
	return ""
}

func (self *tsFieldModel) KeyType() string {
	switch self.Type {
	case model.FieldType_Enum:
		return self.Complex.Name
	case model.FieldType_Int32:
		return "number"
	case model.FieldType_String:
		return "string"
	default:
		return model.FieldTypeToString(self.Type)
	}
}

func (self *tsFieldModel) ElementTypeString() string {
	switch self.Type {
	case model.FieldType_Enum:
		return self.Complex.Name
	case model.FieldType_Struct:
		return self.Complex.Name
	case model.FieldType_Float:
		return "number"
	case model.FieldType_Int32:
		return "number"
	case model.FieldType_String:
		return "string"
	case model.FieldType_Bool:
		return "boolean"
	default:
		return "any"
	}
}

func (self *tsFieldModel) TypeString() string {
	if self.Type == model.FieldType_Map {
		return self.MapTypeString()
	}
	if self.IsRepeated {
		return self.ElementTypeString() + "[]"
	}
	return self.ElementTypeString()
}

func (self *tsFieldModel) MapTypeString() string {
	keyType := self.mapKeyTsType()
	valueType := self.mapValueTsType()
	return "Record<" + keyType + ", " + valueType + ">"
}

func (self *tsFieldModel) mapKeyTsType() string {
	switch self.MapKeyType {
	case model.FieldType_Int32, model.FieldType_Int64, model.FieldType_UInt32, model.FieldType_UInt64, model.FieldType_Float:
		return "number"
	case model.FieldType_String:
		return "string"
	case model.FieldType_Bool:
		return "boolean"
	case model.FieldType_Enum:
		if self.MapKeyComplex != nil {
			return self.MapKeyComplex.Name
		}
		return "number"
	default:
		return "any"
	}
}

func (self *tsFieldModel) mapValueTsType() string {
	switch self.MapValueType {
	case model.FieldType_Int32, model.FieldType_Int64, model.FieldType_UInt32, model.FieldType_UInt64, model.FieldType_Float:
		return "number"
	case model.FieldType_String:
		return "string"
	case model.FieldType_Bool:
		return "boolean"
	case model.FieldType_Enum:
		if self.MapValueComplex != nil {
			return self.MapValueComplex.Name
		}
		return "number"
	case model.FieldType_Struct:
		if self.MapValueComplex != nil {
			return self.MapValueComplex.Name
		}
		return "any"
	default:
		return "any"
	}
}

// TypeScript 索引结构模型
type tsIndexedStructModel struct {
	*model.FieldDescriptor
	Indexes    []*tsFieldModel
	IsVertical bool
}

func (self *tsIndexedStructModel) TypeName() string {
	return self.Complex.Name
}
func (self *tsIndexedStructModel) HasAnyIndex() bool {
	return len(self.FieldDescriptor.Complex.Indexes) > 0
}

func (self *tsIndexedStructModel) TypeString() string {
	if self.Type == model.FieldType_Map {
		return self.mapTypeString()
	}
	if self.IsRepeated {
		return self.elementTypeString() + "[]"
	}
	return self.elementTypeString()
}

func (self *tsIndexedStructModel) elementTypeString() string {
	switch self.Type {
	case model.FieldType_Enum:
		return self.Complex.Name
	case model.FieldType_Struct:
		return self.Complex.Name
	case model.FieldType_Float:
		return "number"
	case model.FieldType_Int32:
		return "number"
	case model.FieldType_String:
		return "string"
	case model.FieldType_Bool:
		return "boolean"
	default:
		return "any"
	}
}

func (self *tsIndexedStructModel) mapTypeString() string {
	keyType := self.mapKeyTsType()
	valueType := self.mapValueTsType()
	return "Record<" + keyType + ", " + valueType + ">"
}

func (self *tsIndexedStructModel) mapKeyTsType() string {
	switch self.MapKeyType {
	case model.FieldType_Int32, model.FieldType_Int64, model.FieldType_UInt32, model.FieldType_UInt64, model.FieldType_Float:
		return "number"
	case model.FieldType_String:
		return "string"
	case model.FieldType_Bool:
		return "boolean"
	case model.FieldType_Enum:
		if self.MapKeyComplex != nil {
			return self.MapKeyComplex.Name
		}
		return "number"
	default:
		return "any"
	}
}

func (self *tsIndexedStructModel) mapValueTsType() string {
	switch self.MapValueType {
	case model.FieldType_Int32, model.FieldType_Int64, model.FieldType_UInt32, model.FieldType_UInt64, model.FieldType_Float:
		return "number"
	case model.FieldType_String:
		return "string"
	case model.FieldType_Bool:
		return "boolean"
	case model.FieldType_Enum:
		if self.MapValueComplex != nil {
			return self.MapValueComplex.Name
		}
		return "number"
	case model.FieldType_Struct:
		if self.MapValueComplex != nil {
			return self.MapValueComplex.Name
		}
		return "any"
	default:
		return "any"
	}
}

// TypeScript 结构体模型
type tsStructModel struct {
	*model.Descriptor
	TSFields []*tsFieldModel
}

func (self *tsStructModel) DefinedTable() string {
	return self.File.Name
}

// TypeScript 文件模型
type tsFileModel struct {
	*model.FileDescriptor
	ToolVersion    string
	IndexedStructs []*tsIndexedStructModel
	All            []*tsIndexedStructModel
	Structs        []*tsStructModel
	Enums          []*tsStructModel
	Verticals      []*tsIndexedStructModel
	Name           string
	PackageName    string
}

func (self *tsFileModel) Package() string {
	// 优先使用命令行指定的包名，如果没有则使用表格中定义的包名
	if self.PackageName != "" {
		return self.PackageName
	}
	return self.FileDescriptor.Pragma.GetString("Package")
}

// 收集索引信息
func collectTSIndexInfo(g *Globals, fm *tsFileModel) {
	for _, fd := range g.CombineStruct.Fields {
		if g.CombineStruct.Usage != model.DescriptorUsage_CombineStruct {
			continue
		}

		if fd.Complex == nil {
			continue
		}

		if !fd.Complex.File.MatchTag(".ts") {
			continue
		}

		// 创建索引结构体模型
		rm := tsIndexedStructModel{
			FieldDescriptor: fd,
			IsVertical:      fd.Complex.File.Pragma.GetBool("Vertical"),
		}

		// 设置索引字段，只收集单个索引字段
		for _, key := range fd.Complex.Indexes {
			rm.Indexes = append(rm.Indexes, &tsFieldModel{
				FieldDescriptor: key,
			})
		}

		// 联合索引字段不需要添加到Indexes中，它们会通过UnionIndexes单独处理

		// 添加到All切片
		fm.All = append(fm.All, &rm)

		// 如果有索引或联合索引，添加到IndexedStructs切片
		if len(fd.Complex.Indexes) > 0 || len(fd.Complex.UnionIndexes) > 0 {
			fm.IndexedStructs = append(fm.IndexedStructs, &rm)
		}
	}
}

// 收集所有结构信息
func collectAllTSStructInfo(g *Globals, fm *tsFileModel) {
	for _, d := range g.FileDescriptor.Descriptors {
		if !d.File.MatchTag(".ts") {
			continue
		}

		structM := &tsStructModel{Descriptor: d}

		for index, fd := range d.Fields {
			field := &tsFieldModel{
				FieldDescriptor: fd,
				Required:        !fd.Meta.GetBool("Optional"),
			}

			switch d.Kind {
			case model.DescriptorKind_Struct:
				field.Number = index + 1
			case model.DescriptorKind_Enum:
				field.Number = int(fd.EnumValue)
			}

			structM.TSFields = append(structM.TSFields, field)
		}

		switch d.Kind {
		case model.DescriptorKind_Struct:
			fm.Structs = append(fm.Structs, structM)
		case model.DescriptorKind_Enum:
			fm.Enums = append(fm.Enums, structM)
		}
	}
}

// TypeScript 打印机
type tsPrinter struct{}

func (self *tsPrinter) Run(g *Globals) *Stream {
	tpl, err := template.New("typescript").Funcs(template.FuncMap{
		"add": func(a, b int) int {
			return a + b
		},
	}).Parse(tsTemplate)
	if err != nil {
		log.Errorln("parse typescript template failed:", err)
		return nil
	}

	var fm tsFileModel
	fm.ToolVersion = g.Version
	fm.FileDescriptor = g.FileDescriptor
	fm.Name = g.FileDescriptor.Pragma.GetString("TableName")
	fm.PackageName = g.PackageName

	collectTSIndexInfo(g, &fm)
	collectAllTSStructInfo(g, &fm)

	bf := NewStream()
	err = tpl.Execute(bf.Buffer(), &fm)
	if err != nil {
		log.Errorln("execute template failed:", err)
		return nil
	}

	return bf
}

func init() {
	RegisterPrinter("ts", &tsPrinter{})
}
