-- Generated by github.com/adamluo159/tabtoy
-- Version: 

local tab = {
	AAA = {
		{ ID = 1, Name = "黑猫警长", SSS = "A", DDD = { X= 2, Y= 3 } 	},
		{ ID = 2, Name = "邋遢大王", SSS = "A1", DDD = { X= 2, Y= 4 } 	},
		{ ID = 3, Name = "邋遢大王", SSS = "A2", DDD = { X= 2, Y= 5 } 	},
		{ ID = 4, Name = "邋遢大王", SSS = "A3", DDD = {  } 	}
	}

}


-- ID
tab.AAAByID = {}
for _, rec in pairs(tab.AAA) do
	tab.AAAByID[rec.ID] = rec
end

tab.Enum = {
	ActorType = {
		[0] = "Leader",
		[2] = "Pig",
		Monkey = 1,
		Hammer = 3,
	},
}

return tab